config/routes.rb
Rails.application.routes.draw do
  post 'newsletter/create', to: 'newsletter#create', as: 'newsletter_create'
  root 'pages#home'
  devise_for :users
  get '/u/:id', to: 'users#profile', as: 'user'

  resources :posts do
    resources :comments
  end

  get 'panel' => 'pages#panel', as: :panel
  get 'search', to: 'search#search'
  get 'search_with_tag', to: 'search#search_with_tag'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/pages/_hero.html.erb
<section class="hero">
    <div class="container">
        <div class="hero-inner">
<div class="hero-copy">
              <h1 class="hero-title mt-0">Cyber Security For Web Developers</h1>
              <p class="hero-paragraph">Keeping Your Code Secure: <span class="text-[#ff8405]">CSFD</span> Way </p>
              <p class="hero-paragraph"><span class="text-[#ff8405]">CSFD</span> is here to accompany you on your journey to specialize in cyber security for developers.</p>
              <div class="hero-cta"><a class="button button-primary" href="<%= new_user_registration_path %>">Sign in</a><a class="button" href="<%= posts_path %>">All Posts</a></div>
</div>
<div class="hero-figure anime-element">
	<svg class="placeholder" width="528" height="396" viewBox="0 0 528 396">
		<rect width="528" height="396" style="fill:transparent;" />
	</svg>
	<div class="hero-figure-box hero-figure-box-01" data-rotation="45deg"></div>
	<div class="hero-figure-box hero-figure-box-02" data-rotation="-45deg"></div>
	<div class="hero-figure-box hero-figure-box-03" data-rotation="0deg"></div>
	<div class="hero-figure-box hero-figure-box-04" data-rotation="-135deg"></div>
	<div class="hero-figure-box hero-figure-box-05"></div>
	<div class="hero-figure-box hero-figure-box-06"></div>
	<div class="hero-figure-box hero-figure-box-07"></div>
	<div class="hero-figure-box hero-figure-box-08" data-rotation="-22deg"></div>
	<div class="hero-figure-box hero-figure-box-09" data-rotation="-52deg"></div>
	<div class="hero-figure-box hero-figure-box-10" data-rotation="-50deg"></div>
</div>
        </div>
    </div>
</section>

app/views/pages/_latest_blog.html.erb
<section class="features section">
   <div class="container">
     <div class="features-inner section-inner has-bottom-divider">
          <div class="features-header text-center">
              <div class="container-sm">
                <h2 class="section-title mt-0">Latest Posts</h2>
              </div>
          </div>
        <div class="features-wrap">
          <% @posts.each do |post, index| %>
            <div class="feature text-center is-revealing">
               <div class="feature-inner">
                 <div class="feature-icon">
                  <% if post.image.present? %>
                    <%= image_tag url_for(post.image), alt: "image-#{post.title}",class: "border-solid border-2 border-blue-500 rounded-lg" %>
                  <% else %>
                    <%= image_tag "https://wallpaperaccess.com/full/1673364.png", class: "border-solid border-2 border-blue-500 rounded-lg" %>
                  <% end %>
                 </div>
                  <h4 class="feature-title mt-24"><%= post.title %></h4>
                  <p class="text-sm mb-0"><%= post.summary.slice(0, 100) %>...</p>
                  <div class="mt-2">
                  <div class="testimonial-item-footer text-xs  flex justify-center items-center">
                    <%= image_tag url_for(User.find(post.user_id).avatar), class: "avatar avatar-small mr-12 w-12 h-12 bg-white rounded-full" %>
                    <%= post.created_at.strftime("%B %d, %Y") %>
                  </div> 
                    <%= link_to 'Read more', post_path(post), class: "button button-primary button-wide-mobile button-sm mt-5" %>

                  </div>
               </div>
            </div>
          <% end %>
         </div>
      </div>
   </div>
</section>

app/views/pages/_navbar.html.erb
<nav id="header" class="w-full z-30 top-0 text-white bg-[#4343bf] shadow-md sticky">
  <div class="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 py-2">
    <div class="pl-4 flex items-center">
      <%= render 'layouts/csfd_svg' %>
    </div>
    <div class="block lg:hidden pr-4">
      <button id="nav-toggle" class="flex items-center p-1 text-pink-800 hover:text-gray-900 focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out">
        <svg class="fill-current h-6 w-6" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <title>Menu</title>
          <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
        </svg>
      </button>
    </div>
    <div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden mt-2 lg:mt-0 bg-white lg:bg-transparent text-black p-4 lg:p-0 z-20" id="nav-content">
      <ul class="list-reset lg:flex justify-end flex-1 items-center">
        <li class="mr-3">
          <%= link_to "Blogs", posts_path, class:"inline-block py-2 px-4 text-white font-bold no-underline" %>
        </li>
        <% if current_user.present? %>
          <li>
            sea
          </li>
        <% else %>
        <li class="mr-3">
          <%= link_to "Sign in", new_user_session_path, class:"inline-block py-2 px-4 text-white font-bold no-underline" %>
        </li>
        <li class="mr-3">
          <%= button_to "Sign up", new_user_registration_path, method: :get, class:"mx-auto lg:mx-0 hover:underline bg-white text-[#4b4dff] font-bold rounded-full mt-4 lg:mt-0 py-4 px-8 shadow opacity-75 focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out" %>
        </li>
        <% end %>
      </ul>

    </div>
  </div>
  <hr class="border-b border-gray-100 opacity-25 my-0 py-0" />

</nav>

app/views/pages/_newsletter.html.erb
<section class="pricing section overflow-hidden">
   <div class="container-sm">
      <div class="pricing-inner section-inner">
         <div class="pricing-header text-center">
            <h2 class="section-title mt-0">Subscribe to Our Newsletter</h2>
            <p class="section-paragraph mb-0">Stay updated with our latest blog posts. Subscribe now!</p>
         </div>
         <div class="pricing-tables-wrap">
            <div class="pricing-table">
              <div class="pricing-table-inner is-revealing">

									<div class="pricing-table-features-title text-xs pt-24 ">
                    <h6 class="text-xs text-white mb-4">Join our newsletter</h6>
									</div>
                 <div class="pricing-table-main">
                   <%= form_with model: Newsletter.new, url: newsletter_create_path, method: :post do |f| %>
                      <label for="hero-field" class="leading-7 text-sm text-wihte">E-Mail Adress</label>
                      <%= f.text_field :email, id:"hero-field", class:"peer h-full w-full border-b border-blue-gray-200 bg-transparent pt-4 pb-1.5 font-sans text-sm font-normal text-blue-gray-700 outline outline-0 transition-all placeholder-shown:border-blue-gray-200 focus:border-gray-900 focus:outline-0 disabled:border-0 disabled:bg-blue-gray-50" %>
                      <%= f.submit "Send",  class:"w-full h-12 mt-6 flex items-center justify-center bg-blue-600 text-white rounded-lg font-semibold text-sm transition duration-150 ease-in-out hover:bg-blue-700" %>
                    <% end %>
                  </div>
                </div>
            </div>
         </div>
      </div>
   </div>
</section>

app/views/pages/home.html.erb
<div class="overflow-x-hidden">
  <%= render 'hero' %>
  <%= render 'latest_blog' %>
  <%= render 'newsletter' %>
</div>

app/views/pages/panel.html.erb
<div class=" min-h-screen">
  <div class="flex justify-between items-center mb-4 px-4 py-2 rounded-lg shadow-md">
  <h1 class="text-2xl font-bold">Posts</h1>
  <%= link_to "Create Post", new_post_path, class: "px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded" %>
</div>
<div class="relative overflow-x-auto">
    <table class="w-full text-sm text-left rtl:text-right">
        <thead class="text-xs text-white uppercase bg-[#4343bf]">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Title
                </th>
                <th scope="col" class="px-6 py-3">
                   Summary 
                </th>
                <th scope="col" class="px-6 pr-3">
                   Actions 
                </th>
              </tr>
        </thead>
        <tbody>
          <% if @posts.empty? %>
            <tr class="border-b">
                <th scope="row" class="px-6 py-4 font-medium">
                    No Posts Found
                </th>
                <td class="px-6 py-4">
                    No Posts Found
                </td>
                <td class="px-6 py-4 flex">
                    No Posts Found
                </td>
            </tr>
          <% else %>
          <% @posts.each do |post| %>
            <tr class=" text-white border-b">
                <th scope="row" class="px-6 py-4 font-medium">
                    <%= post.title %>
                </th>
                <td class="px-6 py-4">
                    <%= post.summary %>
                </td>
                <td class="px-6 py-4 flex">
                    <%= link_to 'Show', post_path(post), class: "mr-2 text-blue-600 hover:text-blue-900 bg-blue-100 hover:bg-blue-200 px-2 py-1 rounded" %>
                    <%= link_to 'Edit', edit_post_path(post), class: "mr-2 text-green-600 hover:text-green-900 bg-green-100 hover:bg-green-200 px-2 py-1 rounded" %>
                    <%= button_to 'Destroy', post_path(post),
                          method: :delete,
                          class: "mr-2 text-red-600 hover:text-red-900 bg-red-100 hover:bg-red-200 px-2 py-1 rounded",
                          data: { confirm: 'Are you sure?' }
                    %>
                </td>
            </tr>
          <% end %>
          <% end %>
        </tbody>
    </table>
  </div>
</div>