config/routes.rb
Rails.application.routes.draw do
  post 'newsletter/create', to: 'newsletter#create', as: 'newsletter_create'
  root 'pages#home'
  devise_for :users
  get '/u/:id', to: 'users#profile', as: 'user'

  resources :posts do
    resources :comments
  end

  get 'panel' => 'pages#panel', as: :panel
  get 'search', to: 'search#search'
  get 'search_with_tag', to: 'search#search_with_tag'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  after_create :send_new_post_email
  has_rich_text :content
  has_one_attached :image
  has_many :comments, dependent: :destroy
  enum tag: %i[xss sqli csrf ssrf rce lfi rfi idor]

  def send_new_post_email
    return if User.find_by(id: user_id).role != 'admin'

    @emails = Newsletter.all
    @emails.each do |email|
      PostNotifierMailer.new_post(self, email.email).deliver_now
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ApplicationHelper
  before_action :set_post, only: %i[show update destroy]
  before_action :authenticate_user_role_is_admin!, except: %i[index show]
  before_action :set_post_with_author, only: %i[edit]
  # GET /posts or /posts.json
  def index
    @posts = Post.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.paginate(page: params[:page], per_page: 4).order('created_at DESC')
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_post_with_author
    @post = Post.find(params[:id])
    return if current_user.present? && (current_user.role == 'admin' || current_user.id == @post.user_id)

    flash[:alert] = 'You are not authorized to access this page.'
    redirect_to root_path
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :image, :summary, :tag)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
    <div class="my-5">
    <%= form.label :summary %>
    <%= form.text_field :summary, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.rich_text_area :content, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :tag %>
    <%= form.select :tag, Post.tags.keys, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<section id="<%= dom_id post %>">
    <article class="flex flex-col shadow my-4">
        <%= image_tag url_for(post.image), class: "w-full h-[40vh]" if post.image.attached? %>
        <div class=" flex flex-col justify-start p-6">
            <h2 href="#" class="text-blue-700 text-sm font-bold uppercase pb-4"><%= post.tag %></h2>
            <h4 class="text-3xl font-bold hover:text-gray-700 pb-4">
                <%= post.title %>
            </h4>
            <p href="#" class="text-sm pb-8">
            By <a href="#" class="font-semibold hover:text-gray-800">
                <% @user = User.find(post.user_id) %>
                <%= @user.first_name %> <%= @user.last_name %>
            </a>, Published on <%= post.created_at.strftime("%B %d, %Y") %>
            </p>
            <p class="pb-3">
                <%= post.content %>
            </p>
        </div>
    </article>
</section>

app/views/posts/_post_for_index.html.erb
<section class="cta section mt-2" id="<%= dom_id post %>">
  <% @user = User.find(post.user_id) %>
  <div class="container flex">
    <% if post.image.attached? %>
      <img class="object-cover w-full lg:w-1/2 rounded-xl border-4 border-solid border-blue-400 rounded-lg" src="<%= url_for(post.image) %>" alt="">
    <% else %>
      <img class="object-cover w-full lg:w-1/2 rounded-xl border-4 border-solid border-blue-400 rounded-lg" src="https://wallpaperaccess.com/full/1673364.png" alt="">
    <% end %>

    <div class="cta-inner section-inner">
      <div class="flex flex-col">
        <span class="inline-flex items-center rounded-md bg-blue-50 px-2 py-1 text-xs font-medium text-blue-700 ring-1 ring-inset ring-green-600/20 w-1/4 text-center aligns-center justify-center">
          <%= post.tag %>
        </span>
        <h3 class=""><%= post.title %></h3>
        <p><%= truncate(post.summary, length: 100) %>...</p>
        <div class="cta-cta">
          <a class="text-blue-500 inline-flex items-center" href="<%= post_path(post) %>">
            Learn More
            <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
              <path d="M5 12h14"></path>
              <path d="M12 5l7 7-7 7"></path>
            </svg>
          </a>
          
          <div class="testimonial-item-footer text-xs  flex justify-center items-center">
              <a href="<%= user_path(@user) %>">

                <%= image_tag url_for(@user.avatar), class: "avatar avatar-small mr-2  w-12 h-12 bg-white rounded-full" %>
              </a>
              <span class="text-white mr-2"><%= @user.first_name %> <%= @user.last_name %></span>
              <%= post.created_at.strftime("%B %d, %Y") %>
            </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/posts/_posts.html.erb
<% posts.each do |post| %>
  <%= render 'posts/post_for_index', post: post %>
<% end %>
<div class="flex justify-center digg_pagination mt-2">
   <%#  TODO: Add pagination for search results %>
   <%= will_paginate posts, page_links: true %>
</div>

app/views/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Show this post", @post, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to posts", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/index.html.erb
<div class="w-full">
   <div class="min-w-full">
      <section class="text-gray-600 body-font overflow-hidden">
         <div class=" mx-auto">
            <div class=" divide-gray-100">
               <div class="flex justify-center">
                  <div class="border-r-solid border-r-4 border-blue-500 p-4 w-[25vw]">
                     <div class="flex">
                        <%= form_with url: search_path, method: :get do |form| %>
                        <div>
                           <%= form.label :search, "Search", class: "block mt-3 text-sm text-white" %>
                        </div>
                        <div class="flex gap-5 m-2">
                           <%= form.text_field :search, class: "w-full px-5 py-1 text-gray-700 bg-white rounded" %>
                           <%= form.submit "Search", class: "p-2 text-[#4343bf] bg-white rounded-md hover:bg-gray-100 hover:text-white" %>
                        </div>
                        <% end %>
                     </div>
                     <div class="flex m-2 flex-wrap justify-center aligns-center">
                        <%= form_with url: search_with_tag_path, method: :get do |form| %>
                        <%  Post.tags.keys.each do |tag| %>
                           <%= form.submit tag, class: "text-[#4343bf] bg-white rounded-md hover:bg-gray-100 hover:text-white uppercase w-1/4 p-4 mt-2" %>
                           <% end %>
                        <% end %>
                     </div>
                  </div>
                  <div id="posts" class="px-12">
                     <%= render 'posts/posts', posts: @posts %>
                  </div>
               </div>
            </div>
         </div>
      </section>
   </div>
</div>

app/views/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Back to posts", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/show.html.erb
<div>
    <div class="relative">
        <%= render @post %>
                <% if current_user.present? %>
        <div>
            <%= render 'comments/form', post: @post, comment: @post.comments.build %>
        </div>
        <% else %>
            <div class="bg-gray-100 min-w-[10vw] max-w-[10vw] rounded-lg h-20 mt-4 flex flex-col justify-center">
                <p class="text-center">You need to <span class="text-[#4343bf] text-lg"><%= link_to 'sign in', new_user_session_path %></span> or  <span class="text-[#4343bf] text-lg"><%= link_to 'sign up', new_user_registration_path %></span> to comment</p>
            </div>
        <% end %>
        <% @comments.each do |comment| %>
            <%= render 'comments/comment', comment: comment, post: @post %>
        <% end %>
        <div class="flex justify-center digg_pagination items-center p-4 rounded-b-lg">
               <%#  TODO: Add pagination for search results %>
                <%= will_paginate @comments, page_links: true %>
        </div>

    </div>
</div>