config/routes.rb
Rails.application.routes.draw do
  post 'newsletter/create', to: 'newsletter#create', as: 'newsletter_create'
  root 'pages#home'
  devise_for :users
  get '/u/:id', to: 'users#profile', as: 'user'

  resources :posts do
    resources :comments
  end

  get 'panel' => 'pages#panel', as: :panel
  get 'search', to: 'search#search'
  get 'search_with_tag', to: 'search#search_with_tag'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_alerts.html.erb
<%# <% if notice  %>
<%# <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert"> %>
<%#   <span class="block sm:inline"><%= notice</span> %>
<%#   <span class="absolute top-0 bottom-0 right-0 px-4 py-3"> %>
<%#     <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg> %>
<%#   </span> %>
<%# </div> %>
<%# <% elsif alert  %>
<%# <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert"> %>
<%#   <span class="block sm:inline"><%= alert </span> %>
<%#   <span class="absolute top-0 bottom-0 right-0 px-4 py-3"> %>
<%#     <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg> %>
<%#   </span> %>
<%# </div> %>
<%# <% end %>

app/views/layouts/_csfd_svg.html.erb
<a class="toggleColour text-white no-underline hover:no-underline font-bold text-2xl lg:text-4xl" href="<%= root_path %>">
  <svg class="fill-current inline" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="80" height="80" viewBox="0 0 100 100">
      <rect width="58" height="41" x="20" y="38" fill="#4b4dff"></rect><path fill="#4343bf" d="M81,82H17V35h64V82z M23,76h52V41H23V76z"></path><path fill="#ff8405" d="M70,35H60v-3c0-6.065-4.935-11-11-11s-11,4.935-11,11v3H28v-3c0-11.579,9.421-21,21-21 s21,9.421,21,21V35z"></path><rect width="4" height="17" x="47" y="50" fill="#edf7f5"></rect><polygon fill="#3abcf8" points="85,86 23,86 23,76 75,76 75,41 85,41"></polygon>
  </svg>
  CSFD
</a>

app/views/layouts/_footer.html.erb
<footer class="site-footer">
            <div class="container">
                <div class="site-footer-inner">
                    <div class="brand footer-brand">
						<a href="#">
							<%= image_tag "icon.svg", class: "header-logo-image w-12 h-12" %>
						</a>
                    </div>
                    <ul class="footer-links list-reset">
                        <li>
                            <a href="#">Contact</a>
                        </li>
                        <li>
                            <a href="#">About us</a>
                        </li>
                        <li>
                            <a href="#">FAQ's</a>
                        </li>
                        <li>
                            <a href="#">Support</a>
                        </li>
                    </ul>
                    <ul class="footer-social-links list-reset">
                        <li>
                            <a href="#">
                                <span class="screen-reader-text">Facebook</span>
                                <svg width="16" height="16" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M6.023 16L6 9H3V6h3V4c0-2.7 1.672-4 4.08-4 1.153 0 2.144.086 2.433.124v2.821h-1.67c-1.31 0-1.563.623-1.563 1.536V6H13l-1 3H9.28v7H6.023z" fill="#0270D7"/>
                                </svg>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="screen-reader-text">Twitter</span>
                                <svg width="16" height="16" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M16 3c-.6.3-1.2.4-1.9.5.7-.4 1.2-1 1.4-1.8-.6.4-1.3.6-2.1.8-.6-.6-1.5-1-2.4-1-1.7 0-3.2 1.5-3.2 3.3 0 .3 0 .5.1.7-2.7-.1-5.2-1.4-6.8-3.4-.3.5-.4 1-.4 1.7 0 1.1.6 2.1 1.5 2.7-.5 0-1-.2-1.5-.4C.7 7.7 1.8 9 3.3 9.3c-.3.1-.6.1-.9.1-.2 0-.4 0-.6-.1.4 1.3 1.6 2.3 3.1 2.3-1.1.9-2.5 1.4-4.1 1.4H0c1.5.9 3.2 1.5 5 1.5 6 0 9.3-5 9.3-9.3v-.4C15 4.3 15.6 3.7 16 3z" fill="#0270D7"/>
                                </svg>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="screen-reader-text">Google</span>
                                <svg width="16" height="16" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M7.9 7v2.4H12c-.2 1-1.2 3-4 3-2.4 0-4.3-2-4.3-4.4 0-2.4 2-4.4 4.3-4.4 1.4 0 2.3.6 2.8 1.1l1.9-1.8C11.5 1.7 9.9 1 8 1 4.1 1 1 4.1 1 8s3.1 7 7 7c4 0 6.7-2.8 6.7-6.8 0-.5 0-.8-.1-1.2H7.9z" fill="#0270D7"/>
                                </svg>
                            </a>
                        </li>
                    </ul>
                    <div class="footer-copyright">&copy; 2019 Solid, all rights reserved</div>
                </div>
            </div>
        </footer>

app/views/layouts/_navbar.html.erb
<nav id="header" class="w-full z-30 top-0 text-white shadow-md sticky">
  <div class="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 py-2">
    <div class="pl-4 flex items-center">
      <%= render 'layouts/csfd_svg' %>
    </div>
    <div class="block lg:hidden pr-4">
      <button id="nav-toggle" class="flex items-center p-1 text-pink-800 hover:text-gray-900 focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out">
        <svg class="fill-current h-6 w-6" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <title>Menu</title>
          <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
        </svg>
      </button>
    </div>
    <div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden mt-2 lg:mt-0 bg-white lg:bg-transparent text-black p-4 lg:p-0 z-20" id="nav-content">
      <ul class="list-reset lg:flex justify-end flex-1 items-center">
        <li class="mr-3">
          <%= link_to "Blogs", posts_path, class:"inline-block py-2 px-4 text-white font-bold no-underline" %>
        </li>
        <%= render 'layouts/session_management' %>
      </ul>

    </div>
  </div>
  <hr class="border-b border-gray-100 opacity-25 my-0 py-0" />
</nav>

app/views/layouts/_session_management.html.erb
<% if current_user.present? %>
   <li>
  <div class="relative inline-block text-left" data-controller="dropdown">
  <div>
    <button type="button" data-action="click->dropdown#toggleMenu" class="inline-flex w-full justify-center rounded-full w-12 h-12 bg-white text-sm font-semibold text-gray-900 shadow-sm ring-2 ring-[#ff8405] hover:bg-gray-50" id="menu-button" aria-expanded="true" aria-haspopup="true">
      <%= image_tag url_for(current_user.avatar), class:"rounded-full w-12 h-12" %>
    </button>
  </div>
   <div data-target="dropdown.menu" class="absolute right-0 z-10 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none hidden" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
     <div class="py-1" role="none">
       <%= link_to "Profile", user_path(current_user), class:"text-gray-700 block px-4 py-2 text-sm" %>
    <% if current_user.role == "reader" %>  
      <%=  link_to "Posts", posts_path, class:"text-gray-700 block px-4 py-2 text-sm" %>
    <% elsif current_user.role == "writer" %>
      <%= link_to "Posts", posts_path, class:"text-gray-700 block px-4 py-2 text-sm" %>
      <%= link_to "Panel", panel_path, class:"text-gray-700 block px-4 py-2 text-sm" %>
    <% elsif current_user.role == "admin" %>  
      <%= link_to "Posts", posts_path, class:"text-gray-700 block px-4 py-2 text-sm" %>
      <%= link_to "Panel", panel_path, class:"text-gray-700 block px-4 py-2 text-sm" %>
    <% end %>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"text-white block w-full text-left px-4 py-2 text-sm bg-[#4b4dff] hover:bg-white hover:text-[#4b4dff]", tabindex:"-1", id:"menu-item-3" %>
    </div>
   </div>
  </li>
</div>
  <% else %>
  <li class="mr-3">
    <%= link_to "Sign in", new_user_session_path, class:"inline-block py-2 px-4 text-white font-bold no-underline" %>
  </li>
  <li class="mr-3">
    <%= button_to "Sign up", new_user_registration_path, method: :get, class:"mx-auto lg:mx-0 hover:underline bg-white text-[#4b4dff] font-bold rounded-full mt-4 lg:mt-0 py-4 px-8 shadow opacity-75 focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out" %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CSFD-Cyber Security for Developers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'icon.svg' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= javascript_importmap_tags %>
  </head>

  <body style="font-family: 'Source Sans Pro', sans-serif;" class="overflow-x-hidden">
    <main>
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/alerts' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </main>
  </body>
</html>